version: "3.9"

services:
  stt_server_1:
    build:
      context: .
      dockerfile: docker/backend_realtimestt/dockerfile
      args:
        APP_PORT: ${STT_PORT_1}
    container_name: stt_server_1
    ports:
      - "${STT_PORT_1}:${STT_PORT_1}"
    runtime: nvidia
    env_file:
      - .env
    environment:
      - APP_PORT=${STT_PORT_1}
      - CUDA_VISIBLE_DEVICES=${GPU_1}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB_STT=${REDIS_DB_STT_1}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./models:/root/.cache
      - ./logs/stt_server_1:/app/logs 
      - ./data/audio_1:/app/audio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://${STT_HOST_1}:${STT_PORT_1}/docs"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped

  llm_container:
    build:
      context: .
      dockerfile: docker/llm_agent/Dockerfile
    container_name: llm_container
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB_STT=${REDIS_DB_STT_1}
      - REDIS_DB_LLM=${REDIS_DB_LLM_1}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs/llm_container:/app/logs
    restart: unless-stopped

  proxy_server:
    build:
      context: .
      dockerfile: docker/backend_proxy/dockerfile
      args:
        APP_PORT: ${PROXY_PORT}
    container_name: proxy_server
    ports: 
      - "${PROXY_PORT}:${PROXY_PORT}"
    env_file:
      - .env
    environment:
      - APP_PORT=${PROXY_PORT}
      - REALTIME_STT_URL=${REALTIME_STT_URL}
    volumes:
      - ./logs/proxy_server:/app/logs
    depends_on:
      - stt_server_1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${PROXY_HOST}:${PROXY_PORT}/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
  # stt_server_2:
  #   build:
  #     context: .
  #     dockerfile: docker/dockerfile
  #     args:
  #       APP_PORT: ${STT_PORT_2}
  #   container_name: stt_server_2
  #   ports:
  #     - "${STT_PORT_2}:${STT_PORT_2}"
  #   runtime: nvidia
  #   env_file:
  #     - .env
  #   environment:
  #     - APP_PORT=${STT_PORT_2}
  #     - CUDA_VISIBLE_DEVICES=${GPU_2}
  #   volumes:
  #     - ./models:/root/.cache
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8002/docs"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # stt_server_3:
  #   build:
  #     context: .
  #     dockerfile: docker/dockerfile
  #     args:
  #       APP_PORT: ${STT_PORT_3}
  #   container_name: stt_server_3
  #   ports:
  #     - "${STT_PORT_3}:${STT_PORT_3}"
  #   runtime: nvidia
  #   env_file:
  #     - .env
  #   environment:
  #     - APP_PORT=${STT_PORT_3}
  #     - CUDA_VISIBLE_DEVICES=${GPU_3}
  #   volumes:
  #     - ./models:/root/.cache
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8003/docs"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
