FROM python:3.11-slim

WORKDIR /app

# 시스템 패키지 설계
RUN apt-get update && apt-get install -y \
    curl git && \
    rm -rf /var/lib/apt/lists/*

# requirements.txt 디렉토리 복사 및 의존성 설치
COPY requirements requirements
RUN pip install --no-cache-dir -r requirements/requirements-proxy.txt

#  애플리케이션 코드 복사
COPY . .

# 환경변수 설정 (빌드 시 전달 가능)
ARG PROXY_PORT
ENV PROXY_PORT=$PROXY_PORT

EXPOSE ${PROXY_PORT}

# 프록시 FastAPI 앱 실행
ENTRYPOINT sh -c 'uvicorn backend_proxy.main:app --host 0.0.0.0 --port ${PROXY_PORT}'