FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

WORKDIR /app


RUN apt-get update && \
    apt-get install -y \
        python3 python3-pip \
        ffmpeg portaudio19-dev git && \
    rm -rf /var/lib/apt/lists/*

# CUDA 12.1용 PyTorch
RUN pip install torch==2.5.1+cu121 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu121

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install RealtimeSTT --no-deps

COPY . .

# --- 환경 변수 설정 (빌드 타임 ARG -> 런타임 ENV)
ARG APP_PORT
ENV APP_PORT=$APP_PORT

EXPOSE ${APP_PORT}

ENTRYPOINT sh -c 'uvicorn main:app --host 0.0.0.0 --port ${APP_PORT}'
